image:
  - Visual Studio 2019

install:
  - choco install gitversion.portable -pre -y

before_build:
  - cmd: gitversion /l console /output buildserver

build_script:
  - ps: .\build.ps1 Pack

artifacts:
  - path: artifacts/Luxa4Slack-*.zip
    name: Artifact