version: 1.0.6.{build}

assembly_info:
  patch: true
  file: GlobalAssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

configuration: Release
platform: Any CPU

before_build:
- cmd: >-
    dotnet restore

build:
  project: Luxa4Slack.sln
  verbosity: minimal

after_build:
- cmd: >-
    del /Q bin\Release\*.xml

    del /Q bin\Release\*.pdb

    7z a Luxa4Slack-%APPVEYOR_BUILD_VERSION%.zip %CD%\bin\Release\*

artifacts:
- path: Luxa4Slack-*.zip
  name: Luxa4Slack

deploy:
- provider: GitHub
  auth_token:
    secure: fUfvn0AxoiLyyw4vz+0XESvl/FibBKHSfQwAYquPQqI9AwHhoPd4qNZonfjvLTuf
  artifact: Luxa4Slack
  draft: true
  on:
    branch: master
    appveyor_repo_tag: true
